title = "basic gitleaks config"

[[rules]]
id = "github-pat"
description = "GitHub Personal Access Token"
regex = '''(?i)ghp_[A-Za-z0-9]{36}'''
tags = ["github","key"]

[[rules]]
id = "aws-access-key-id"
description = "AWS Access Key ID"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws","key"]

[[rules]]
id = "aws-secret-access-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws(.{0,20})?(secret|session)?(.{0,20})?(key|access)[^a-z0-9]{0,5}([A-Za-z0-9/+=]{40})'''
secretGroup = 5
tags = ["aws","key"]

[[rules]]
id = "google-api-key"
description = "Google API Key"
regex = '''AIza[0-9A-Za-z_\-]{35}'''
tags = ["google","key"]

[[rules]]
id = "private-key-block"
description = "Private Key (PEM/SSH)"
regex = '''-----BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY-----'''
tags = ["private","key"]

[allowlist]
paths = [
  '''^EVIDENCE/''',
  '''\.md$''',
  '''\.png$''', '''\.jpg$''', '''\.jpeg$''', '''\.gif$''', '''\.svg$'''
]
